test_extcall
() {}
(1,) {}
(1, 2) {}
(1, 2, 3) {}
(1, 2, 3, 4, 5) {}
(1, 2, 3, 4, 5) {}
(1, 2, 3, 4, 5) {}
(1, 2, 3) {'b': 5, 'a': 4}
(1, 2, 3, 4, 5) {'b': 7, 'a': 6}
(1, 2, 3, 6, 7) {'y': 5, 'b': 9, 'x': 4, 'a': 8}
TypeError: not enough arguments to g(); expected 1, got 0
TypeError: not enough arguments to g(); expected 1, got 0
TypeError: not enough arguments to g(); expected 1, got 0
1 () {}
1 (2,) {}
1 (2, 3) {}
1 (2, 3, 4, 5) {}
0 (1, 2) {}
1 () {'d': 4, 'b': 2, 'c': 3, 'a': 1}
{'b': 2, 'c': 3, 'a': 1}
{'b': 2, 'c': 3, 'a': 1}
keyword parameter 'x' redefined in call to g()
keyword parameter 'b' redefined in function call
keywords must be strings
h() got an unexpected keyword argument 'e'
* argument must be a sequence
** argument must be a dictionary
3 512 1
3
3
unbound method must be called with instance as first argument
unbound method must be called with instance as first argument
